language: perl6
perl6:
  - '2020.01'
  - '2019.11'
  - '2019.07.1'
  - '2019.03'
  - latest
install:
  - sudo apt-get install libhidapi-dev
  - rakudobrew build-zef
  - zef install --depsonly .
  - zef build .
script:
  - prove -v -e "perl6 --ll-exception -Ilib" t
after_success:
  - zef list --installed --verbose
